start: expr

expr: expr "+" term   -> add_expr
    | expr "-" term   -> sub_expr
    | term

term: term "*" factor -> mul_expr
    | factor

factor: roll
      | NUMBER        -> number
      | "(" expr ")"

roll: NUMBER "d" NUMBER modifier*

modifier: "ex"            -> explode
        | "kb" NUMBER     -> keep_biggest
        | "ks" NUMBER     -> keep_smallest
        | "r" COMP NUMBER -> reroll
        | "rr" COMP NUMBER -> recursive_reroll
        | "min" NUMBER    -> min_value
        | "max" NUMBER    -> max_value

COMP: "<" | ">"

%import common.INT -> NUMBER
%import common.WS
%ignore WS
